### ISSUE TITLE
[createS3Bucket] The bucket you tried to delete is not empty

### ISSUE THREAD

**Issue by rezabekf** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#15]
Stack fails to delete due to a S3 bucket not being empty.

Replication:
Delete deployed stack.

Proposed resolution:
Consider adding code below to the `createS3Bucket` resource:
```
createS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    {...}
```
